server:
  port: 9091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data_service?useSSL=false
    username: postgres
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
jwt:
  header: Authorization
  secret: SecretKeyToGenJWTs
  expiration: 864000000
