server:
  port: 9091

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/data_service
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true